version: "3.0"
services:
  front-end:
    container_name: frontend
    build: ./front-end
    expose:
      - "3000"
    ports:
      - 3000:3000
    working_dir: /frontend
    depends_on:
      back-end:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
  back-end:
    container_name: backend
    build: ./back-end
    expose:
      - "3001"
    ports:
      - 3001:3001
    working_dir: /backend
    command: yarn run dev
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=3001
      - JWT_SECRET=jwt_secret
      - DB_USER=postgres
      - DB_PASS=docker
      - DB_HOST=db
      - DB_PORT=5432
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  db:
    image: "postgres:14.2-alpine"
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - PGDATABASE=postgres
    ports:
      - "5433:5432"
    restart: "always"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      timeout: 10s
      retries: 5
