version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./src:/app
    depends_on:
      - db
  db:
    container_name: "postgres"
    image: postgres
    restart: always
    ports:
      - "5433:5431"
    environment:
      - POSTGRES_PASSWORD=docker
  dbadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin4
